//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPlan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        public System.Guid Id { get; set; }
        public string BarCode { get; set; }
        public System.Guid StyleId { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> LinkingStartAt { get; set; }
        public Nullable<System.Guid> LinkingBy { get; set; }
        public Nullable<System.DateTime> LinkingEndAt { get; set; }
        public string KnittingMachine { get; set; }
        public System.Guid OperatorId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdateInfo { get; set; }
    }
}
