//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPlan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public System.Guid Id { get; set; }
        public System.Guid SellerId { get; set; }
        public System.Guid OrderId { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string UpdateInfo { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
