//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPlan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public System.Guid Id { get; set; }
        public string BarCode { get; set; }
        public string Name { get; set; }
        public System.Guid BuyerId { get; set; }
        public string YarnType { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ProductionStartAt { get; set; }
        public Nullable<System.DateTime> ProductionEndAt { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public Nullable<System.DateTime> ShippedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdateInfo { get; set; }
        public decimal Quantity { get; set; }
        public int Status { get; set; }
    }
}
